name: SampleSolution
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - pytorch=1.8
  - torchvision=0.9
  - cudatoolkit=11.1

  - matplotlib
  - numpy
  - pillow
  - pyyaml
  - scipy
  - tensorboard
  - tqdm

  - wandb
  - seaborn
  - pandas
  - easydict

  - pip:
    - opencv-python>=4.1.2